#version of docker compose
version: '2'

#Declare networks & volumes initially
networks:
  mysql_net:
    driver: bridge

volumes:
  mysql-service-volume: { }

services:
  mysql-service:
    image: mysql:8.0.31
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=P4ssw0rd
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=P4ssw0rd
    networks:
      - mysql_net
    volumes:
      - mysql-service-volume:/var/lib/mysql
      - ./docker-script/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql





