#*************************************************************
#************************ About author ***********************
Author=gentjan kolicaj


#**************************************************************
#************************** Database **************************
#**************************************************************
Api=jdbc
Database=mysql
Server=localhost
Port=3306
User=root
Password=toor8


#**************************************************************
#************************** Application ***********************
#**************************************************************
License=2dfgdfgagfdsgdsfgstertgyhdttye434435



#**************************************************************
#************************** PRINT CONFIGS********************
#**************************************************************
PRINT_EXCEPTION=true
PRINT_FILE_IO=true
PRINT_DATABASE_QUERY=true
PRINT_DATABASE_IO=true
PRINT_LOG=true
PRINT_OTHER=true
PRINT_QUERY_RESULTS=true
PRINT_FORMAT=NORMAL
PRINT_ENV=CONSOLE


