-- MySQL Script generated by MySQL Workbench
-- Sat Mar 31 20:25:34 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward   ering


-- -----------------------------------------------------
-- Schema mymanager
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS mymanager;

-- -----------------------------------------------------
-- Schema mymanager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS mymanager ;


-- -----------------------------------------------------
-- Table   mymanager  .  jobs  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  jobs   (
    job_id   INT NOT NULL ,
    job_title   VARCHAR(60) NOT NULL,
    min_salary   FLOAT NULL,
    max_salary   FLOAT NULL,
    created_by   VARCHAR(60) NOT NULL,
    created_date   DATE NOT NULL,
    updated_by   VARCHAR(60) NULL,
    updated_date   DATE NULL,
  PRIMARY KEY (  job_id  ));



-- -----------------------------------------------------
-- Table   mymanager  .  departments  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  departments   (
    department_id   INT NOT NULL   ,
    department_name   VARCHAR(60) NULL,
    manager_id   VARCHAR(60) NULL,
    created_by   VARCHAR(60) NOT NULL,
    created_date   DATE NOT NULL,
    updated_by   VARCHAR(60) NULL,
    updated_date   DATE NULL,
  PRIMARY KEY (  department_id  ));



-- -----------------------------------------------------
-- Table   mymanager  .  countries  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  countries   (
    country   VARCHAR(20) NOT NULL,
  PRIMARY KEY (  country  ));



-- -----------------------------------------------------
-- Table   mymanager  .  projects  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  projects   (
    project_name   VARCHAR(60) NOT NULL,
    description   TEXT NULL,
    customer   VARCHAR(60) NOT NULL,
    country   VARCHAR(20) NOT NULL,
    created_by   VARCHAR(60) NOT NULL,
    created_date   DATE NOT NULL,
    updated_by   VARCHAR(60) NULL,
    updated_date   DATE NULL,
  PRIMARY KEY (  project_name  ),
    FOREIGN KEY (  country  )
    REFERENCES   mymanager  .  countries   (  country  ));


-- -----------------------------------------------------
-- Table   mymanager  .  employees  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  employees   (
    employee_id   VARCHAR(60) NOT NULL,
    first_name   VARCHAR(60) NOT NULL,
    last_name   VARCHAR(60) NOT NULL,
    middle_name   VARCHAR(60) NULL,
    birthday   DATE NOT NULL,
    birthplace   VARCHAR(100) NOT NULL,
    gender   VARCHAR( 2)NOT NULL,
    job_id   INT NOT NULL,
    department_id   INT NOT NULL,
    project_name   VARCHAR(60) NOT NULL,
    created_by   VARCHAR(60) NOT NULL,
    created_date   DATE NOT NULL,
    updated_by   VARCHAR(60) NULL,
    updated_date   DATE NULL,
  PRIMARY KEY (  employee_id  ),
    FOREIGN KEY (  job_id  )
    REFERENCES   mymanager  .  jobs   (  job_id  ),
    FOREIGN KEY (  department_id  )
    REFERENCES   mymanager  .  departments   (  department_id  ),
    FOREIGN KEY (  project_name  )
    REFERENCES   mymanager  .  projects   (  project_name  ));


-- -----------------------------------------------------
-- Table   mymanager  .  employee_adress  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  employee_adress   (
    employee_id   VARCHAR(60) NOT NULL,
    country   VARCHAR(20) NOT NULL,
    city   VARCHAR(60) NOT NULL,
    street_name   VARCHAR(60) NOT NULL,
    zipcode   INT NULL,
    building   VARCHAR(60) NULL,
    created_by   VARCHAR(60) NOT NULL,
    created_date   DATE NOT NULL,
    updated_by   VARCHAR(60) NULL,
    updated_date   DATE NULL,
  PRIMARY KEY (  employee_id  ),
    FOREIGN KEY (  employee_id  )
    REFERENCES   mymanager  .  employees   (  employee_id  ),
    FOREIGN KEY (  country  )
    REFERENCES   mymanager  .  countries   (  country  )    );


-- -----------------------------------------------------
-- Table   mymanager  .  employee_contact  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  employee_contact   (
    employee_id   VARCHAR(60) NOT NULL,
    telephone   INT NULL,
    celular     INT NOT NULL,
    email   VARCHAR(60) NOT NULL,
    fax   VARCHAR(60) NULL,
    created_by   VARCHAR(60) NOT NULL,
    created_date   DATE NOT NULL,
    updated_by   VARCHAR(60) NULL,
    updated_date   DATE NULL,
  PRIMARY KEY (  employee_id  ),
   FOREIGN KEY (  employee_id  )
    REFERENCES   mymanager  .  employees   (  employee_id  )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)  ;


-- -----------------------------------------------------
-- Table   mymanager  .  file_types  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  file_types   (
    file_type   VARCHAR(5) NOT NULL,
  PRIMARY KEY (  file_type  ))        ;


-- -----------------------------------------------------
-- Table   mymanager  .  employee_documents  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  employee_documents   (
    document_name   TEXT NULL,
    document_type   VARCHAR(45) NOT NULL,
    document_file   bytea NULL,
    file_type   VARCHAR(5) NOT NULL,
    document_number     INT NOT NULL   ,
    employee_id   VARCHAR(60) NOT NULL,
    created_by   VARCHAR(60) NOT NULL,
    created_date   DATE NOT NULL,
    updated_by   VARCHAR(60) NULL,
    updated_date   DATE NULL,
    PRIMARY KEY (  document_number  ),
       FOREIGN KEY (  employee_id  )
    REFERENCES   mymanager  .  employees   (  employee_id  )   ,
      FOREIGN KEY (  file_type  )
    REFERENCES   mymanager  .  file_types   (  file_type  )
   ) ;


-- -----------------------------------------------------
-- Table   mymanager  .  job_history  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  job_history   (
    employee_id   VARCHAR(60) NOT NULL,
    start_date   DATE NULL,
    end_date   DATE NULL,
    job_id   VARCHAR(45) NULL,
    department_id   VARCHAR(45) NULL,
    created_by   VARCHAR(60) NOT NULL,
    created_date   DATE NOT NULL,
    updated_by   VARCHAR(60) NULL,
    updated_date   DATE NULL,
    FOREIGN KEY (  employee_id  )
    REFERENCES   mymanager  .  employees   (  employee_id  )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)   ;


-- -----------------------------------------------------
-- Table   mymanager  .  employee_additional  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  employee_additional   (
    employee_id   VARCHAR(60) NOT NULL,
    salary_amount   FLOAT NULL,
    hire_date   DATE NOT NULL,
    created_by   VARCHAR(60) NOT NULL,
    created_date   DATE NOT NULL,
    updated_by   VARCHAR(60) NULL,
    updated_date   DATE NULL,
    PRIMARY KEY (  employee_id  ),
    FOREIGN KEY (  employee_id  )
    REFERENCES   mymanager  .  employees   (  employee_id  )
   )  ;


-- -----------------------------------------------------
-- Table   mymanager  .  user_type  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  user_type   (
    user_type   VARCHAR(10) NOT NULL,
  PRIMARY KEY (  user_type  ))     ;


-- -----------------------------------------------------
-- Table   mymanager  .  users  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  users   (
    user_id   VARCHAR(60) NOT NULL,
    user_type   VARCHAR(10) NOT NULL,
    first_name   VARCHAR(60) NOT NULL,
    last_name   VARCHAR(60) NOT NULL,
    password   VARCHAR(60) NOT NULL,
    birthday   DATE NOT NULL,
    birthplace   VARCHAR(100) NOT NULL,
    gender   VARCHAR(2) NOT NULL,
    rights   VARCHAR(60) NOT NULL,
    created_by   VARCHAR(60) NOT NULL,
    created_date   DATE NOT NULL,
    updated_by   VARCHAR(60) NULL,
    updated_date   DATE NULL,
    PRIMARY KEY (  user_id  ),
    FOREIGN KEY (  user_type  )
    REFERENCES   mymanager  .  user_type   (  user_type  ));


-- -----------------------------------------------------
-- Table   mymanager  .  user_contact  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  user_contact   (
    user_id   VARCHAR(60) NOT NULL,
    telephone   INT NULL,
    celular   INT NOT NULL,
    email   VARCHAR(60) NOT NULL,
    fax   VARCHAR(60) NULL,
    created_by   VARCHAR(60) NOT NULL,
    created_date   DATE NOT NULL,
    updated_by   VARCHAR(60) NULL,
    updated_date   DATE NULL,
    PRIMARY KEY (  user_id  ),
    FOREIGN KEY (  user_id  )
    REFERENCES   mymanager  .  users   (  user_id  )) ;


-- -----------------------------------------------------
-- Table   mymanager  .  user_adress  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  user_adress   (
    user_id   VARCHAR(60) NOT NULL,
    country   VARCHAR(20) NOT NULL,
    city   VARCHAR(60) NOT NULL,
    street_name   VARCHAR(60) NOT NULL,
    zipcode   INT NULL,
    building   VARCHAR(60) NULL,
    created_by   VARCHAR(60) NOT NULL,
    created_date   DATE NOT NULL,
    updated_by   VARCHAR(60) NULL,
    updated_date   DATE NULL,
  PRIMARY KEY (  user_id  ),
     FOREIGN KEY (  user_id  )
    REFERENCES   mymanager  .  users   (  user_id  )   ,
     FOREIGN KEY (  country  )
    REFERENCES   mymanager  .  countries   (  country  )   )   ;


-- -----------------------------------------------------
-- Table   mymanager  .  attempts  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  attempts   (
    index   INT NOT NULL   ,
    "user"   VARCHAR(60) NOT NULL,
    password   VARCHAR(60) NOT NULL,
    status   VARCHAR(10) NOT NULL,
    description   VARCHAR(100) NULL,
    date_time   DATE NOT NULL,
  PRIMARY KEY (  index  )) ;


-- -----------------------------------------------------
-- Table   mymanager  .  users_history  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  users_history   (
    user_id   VARCHAR(60) NOT NULL,
    user_type   VARCHAR(60) NOT NULL,
    first_name   VARCHAR(60) NOT NULL,
    last_name   VARCHAR(60) NOT NULL,
    password   VARCHAR(60) NOT NULL,
    birthday   DATE NULL,
    birthplace   VARCHAR(100) NULL,
    gender   VARCHAR(2) NOT NULL,
    rights   VARCHAR(60) NOT NULL,
    created_by   VARCHAR(60) NOT NULL,
    created_date   DATE NOT NULL,
    updated_by   VARCHAR(60) NULL,
    updated_date   DATE NULL) ;


-- -----------------------------------------------------
-- Table   mymanager  .  user_contact_history  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  user_contact_history   (
    user_id   VARCHAR(60) NOT NULL,
    telephone   INT NULL,
    celular   INT NOT NULL,
    email   VARCHAR(60) NOT NULL,
    fax   VARCHAR(60) NULL,
    created_by   VARCHAR(60) NOT NULL,
    created_date   DATE NOT NULL,
    updated_by   VARCHAR(60) NULL,
    updated_date   DATE NULL) ;


-- -----------------------------------------------------
-- Table   mymanager  .  user_adress_history  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  user_adress_history   (
    user_id   VARCHAR(60) NOT NULL,
    country   VARCHAR(20) NOT NULL,
    city   VARCHAR(60) NOT NULL,
    street_name   VARCHAR(60) NOT NULL,
    zipcode   INT NULL,
    building   VARCHAR(60) NULL,
    created_by   VARCHAR(60) NOT NULL,
    created_date   DATE NOT NULL,
    updated_by   VARCHAR(60) NULL,
    updated_date   DATE NULL) ;


-- -----------------------------------------------------
-- Table   mymanager  .  payment_type  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  payment_type   (
    payment_type   VARCHAR(10) NOT NULL,
  PRIMARY KEY (  payment_type  )) ;


-- -----------------------------------------------------
-- Table   mymanager  .  currencies  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  currencies   (
    currency   VARCHAR(10) NOT NULL,
  PRIMARY KEY (  currency  ))  ;


-- -----------------------------------------------------
-- Table   mymanager  .  employee_payments  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  employee_payments   (
    payment_id   INT NOT NULL,
    payment_type   VARCHAR(10) NOT NULL,
    employee_id   VARCHAR(60) NOT NULL,
    currency   VARCHAR(10) NOT NULL,
    payment_amount   FLOAT NOT NULL,
    payment_desc   TEXT NOT NULL,
    created_by   VARCHAR(60) NOT NULL,
    created_date   DATE NOT NULL,
    updated_by   VARCHAR(60) NULL,
    updated_date   DATE NULL,
  PRIMARY KEY (  payment_id  ), 
    FOREIGN KEY (  payment_type  )
    REFERENCES   mymanager  .  payment_type   (  payment_type  )    ,
    FOREIGN KEY (  employee_id  )
    REFERENCES   mymanager  .  employees   (  employee_id  )    ,
    FOREIGN KEY (  currency  )
    REFERENCES   mymanager  .  currencies   (  currency  )   ) ;


-- -----------------------------------------------------
-- Table   mymanager  .  working_hours  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  working_hours   (
    index   INT NOT NULL,
    employee_id   VARCHAR(60) NOT NULL,
    date   DATE NOT NULL,
    amount   FLOAT NOT NULL,
    created_by   VARCHAR(60) NOT NULL,
    created_date   DATE NOT NULL,
    update_by   VARCHAR(60) NULL,
    updated_date   DATE NULL,
  PRIMARY KEY (  index  ),
    FOREIGN KEY (  employee_id  )
    REFERENCES   mymanager  .  employees   (  employee_id  )
    ) ;


-- -----------------------------------------------------
-- Table   mymanager  .  employee_additional_history  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  employee_additional_history   (
    employee_id   VARCHAR(60) NOT NULL,
    salary_amount   FLOAT NULL,
    hire_date   DATE NOT NULL,
    created_by   VARCHAR(60) NOT NULL,
    created_date   DATE NOT NULL,
    updated_by   VARCHAR(60) NULL,
    updated_date   DATE NULL) ;


-- -----------------------------------------------------
-- Table   mymanager  .  job_history_history  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  job_history_history   (
    employee_id   VARCHAR(60) NOT NULL,
    start_date   DATE NULL,
    end_date   DATE NULL,
    job_id   VARCHAR(45) NULL,
    department_id   VARCHAR(45) NULL,
    created_by   VARCHAR(60) NOT NULL,
    created_date   DATE NOT NULL,
    updated_by   VARCHAR(60) NULL,
    updated_date   DATE NULL) ;


-- -----------------------------------------------------
-- Table   mymanager  .  employee_adress_history  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  employee_adress_history   (
    employee_id   VARCHAR(60) NOT NULL,
    country   VARCHAR(20) NOT NULL,
    city   VARCHAR(60) NOT NULL,
    street_name   VARCHAR(60) NOT NULL,
    zipcode   INT NULL,
    building   VARCHAR(60) NULL,
    created_by   VARCHAR(60) NOT NULL,
    created_date   DATE NOT NULL,
    updated_by   VARCHAR(60) NULL,
    updated_date   DATE NULL)  ;


-- -----------------------------------------------------
-- Table   mymanager  .  employee_contact_history  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  employee_contact_history   (
    employee_id   VARCHAR(60) NOT NULL,
    telephone   INT NULL,
    celular   INT NOT NULL,
    email   VARCHAR(60) NOT NULL,
    fax   VARCHAR(60) NULL,
    created_by   VARCHAR(60) NOT NULL,
    created_date   DATE NOT NULL,
    updated_by   VARCHAR(60) NULL,
    updated_date   DATE NULL) ;


-- -----------------------------------------------------
-- Table   mymanager  .  employees_history  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  employees_history   (
    employee_id   VARCHAR(60) NOT NULL,
    first_name   VARCHAR(60) NOT NULL,
    last_name   VARCHAR(60) NOT NULL,
    middle_name   VARCHAR(60) NULL,
    birthday   DATE NOT NULL,
    birthplace   VARCHAR(100) NOT NULL,
    gender   VARCHAR(2) NOT NULL,
    job_id   INT NOT NULL,
    department_id   INT NOT NULL,
    project_name   VARCHAR(60) NOT NULL,
    created_by   VARCHAR(60) NOT NULL,
    created_date   DATE NOT NULL,
    updated_by   VARCHAR(60) NULL,
    updated_date   DATE NULL) ;


-- -----------------------------------------------------
-- Table   mymanager  .  employee_documents_history  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  employee_documents_history   (
    document_name   TEXT NULL,
    document_type   VARCHAR(45) NOT NULL,
    document_file   bytea NULL,
    file_type   VARCHAR(5) NOT NULL,
    document_number   INT NOT NULL,
    employee_id   VARCHAR(60) NOT NULL,
    created_by   VARCHAR(60) NOT NULL,
    created_date   DATE NOT NULL,
    updated_by   VARCHAR(60) NULL,
    updated_date   DATE NULL)  ;


-- -----------------------------------------------------
-- Table   mymanager  .  employee_payments_history  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  employee_payments_history   (
    payment_id   INT NOT NULL,
    payment_type   VARCHAR(10) NOT NULL,
    employee_id   VARCHAR(60) NOT NULL,
    currency   VARCHAR(10) NOT NULL,
    payment_amount   FLOAT NOT NULL,
    payment_desc   TEXT NOT NULL,
    created_by   VARCHAR(60) NOT NULL,
    created_date   DATE NOT NULL,
    updated_by   VARCHAR(60) NULL,
    updated_date   DATE NULL) ;


-- -----------------------------------------------------
-- Table   mymanager  .  working_hours_history  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  working_hours_history   (
    index   INT NOT NULL,
    employee_id   VARCHAR(60) NOT NULL,
    date   DATE NOT NULL,
    amount   FLOAT NOT NULL,
    created_by   VARCHAR(60) NOT NULL,
    created_date   DATE NOT NULL,
    update_by   VARCHAR(60) NULL,
    updated_date   DATE NULL) ;


-- -----------------------------------------------------
-- Table   mymanager  .  jobs_history  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  jobs_history   (
    job_id   INT NOT NULL,
    job_title   VARCHAR(60) NOT NULL,
    min_salary   FLOAT NULL,
    max_salary   FLOAT NULL,
    created_by   VARCHAR(60) NOT NULL,
    created_date   DATE NOT NULL,
    updated_by   VARCHAR(60) NULL,
    updated_date   DATE NULL) ;


-- -----------------------------------------------------
-- Table   mymanager  .  departments_history  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  departments_history   (
    department_id   INT NOT NULL,
    department_name   VARCHAR(60) NULL,
    manager_id   VARCHAR(60) NULL,
    created_by   VARCHAR(60) NOT NULL,
    created_date   DATE NOT NULL,
    updated_by   VARCHAR(60) NULL,
    updated_date   DATE NULL);


-- -----------------------------------------------------
-- Table   mymanager  .  employee_additional_history  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS   mymanager  .  employee_additional_history   (
    employee_id   VARCHAR(60) NOT NULL,
    salary_amount   FLOAT NULL,
    hire_date   DATE NOT NULL,
    created_by   VARCHAR(60) NOT NULL,
    created_date   DATE NOT NULL,
    updated_by   VARCHAR(60) NULL,
    updated_date   DATE NULL)  ;


