-- MySQL Script generated by MySQL Workbench
-- Wed 11 Jan 2023 05:27:50 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mymanager
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mymanager` ;

-- -----------------------------------------------------
-- Schema mymanager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mymanager` DEFAULT CHARACTER SET utf8 ;
USE `mymanager` ;

-- -----------------------------------------------------
-- Table `mymanager`.`attempts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`attempts` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`attempts` (
  `index` INT(100) NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(60) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `status` ENUM('SUCCESS', 'FAILURE') NOT NULL,
  `description` VARCHAR(100) NULL,
  `date_time` DATETIME NOT NULL,
  PRIMARY KEY (`index`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`countries` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`countries` (
  `country` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`country`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`currencies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`currencies` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`currencies` (
  `currency` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`currency`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`departments` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`departments` (
  `department_id` INT NOT NULL AUTO_INCREMENT,
  `department_name` VARCHAR(60) NULL,
  `manager_id` VARCHAR(60) NULL,
  `created_by` VARCHAR(60) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_by` VARCHAR(60) NULL,
  `updated_date` DATETIME NULL,
  PRIMARY KEY (`department_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`departments_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`departments_history` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`departments_history` (
  `department_id` INT NOT NULL,
  `department_name` VARCHAR(60) NULL,
  `manager_id` VARCHAR(60) NULL,
  `created_by` VARCHAR(60) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_by` VARCHAR(60) NULL,
  `updated_date` DATETIME NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`employee_additional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`employee_additional` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`employee_additional` (
  `employee_id` VARCHAR(60) NOT NULL,
  `salary_amount` FLOAT NULL,
  `hire_date` DATE NOT NULL,
  `created_by` VARCHAR(60) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_by` VARCHAR(60) NULL,
  `updated_date` DATETIME NULL,
  PRIMARY KEY (`employee_id`),
  CONSTRAINT `fk_employee_salary_employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mymanager`.`employees` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`employee_additional_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`employee_additional_history` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`employee_additional_history` (
  `employee_id` VARCHAR(60) NOT NULL,
  `salary_amount` FLOAT NULL,
  `hire_date` DATE NOT NULL,
  `created_by` VARCHAR(60) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_by` VARCHAR(60) NULL,
  `updated_date` DATETIME NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`employee_additional_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`employee_additional_history` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`employee_additional_history` (
  `employee_id` VARCHAR(60) NOT NULL,
  `salary_amount` FLOAT NULL,
  `hire_date` DATE NOT NULL,
  `created_by` VARCHAR(60) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_by` VARCHAR(60) NULL,
  `updated_date` DATETIME NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`employee_adress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`employee_adress` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`employee_adress` (
  `adress_id` INT(200) NOT NULL AUTO_INCREMENT,
  `employee_id` VARCHAR(60) NOT NULL,
  `country` VARCHAR(20) NOT NULL,
  `city` VARCHAR(60) NOT NULL,
  `street_name` VARCHAR(60) NOT NULL,
  `zipcode` INT NULL,
  `building` VARCHAR(60) NULL,
  `created_by` VARCHAR(60) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_by` VARCHAR(60) NULL,
  `updated_date` DATETIME NULL,
  INDEX `fk_employee_adress_countries1_idx` (`country` ASC) VISIBLE,
  PRIMARY KEY (`adress_id`),
  INDEX `fk_employee_adress_employees1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_adress_countries1`
    FOREIGN KEY (`country`)
    REFERENCES `mymanager`.`countries` (`country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_adress_employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mymanager`.`employees` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`employee_adress_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`employee_adress_history` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`employee_adress_history` (
  `adress_id` INT(200) NOT NULL,
  `employee_id` VARCHAR(60) NOT NULL,
  `country` VARCHAR(20) NOT NULL,
  `city` VARCHAR(60) NOT NULL,
  `street_name` VARCHAR(60) NOT NULL,
  `zipcode` INT NULL,
  `building` VARCHAR(60) NULL,
  `created_by` VARCHAR(60) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_by` VARCHAR(60) NULL,
  `updated_date` DATETIME NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`employee_contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`employee_contact` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`employee_contact` (
  `contact_id` INT(200) NOT NULL AUTO_INCREMENT,
  `employee_id` VARCHAR(60) NOT NULL,
  `telephone` INT(20) NULL,
  `celular` INT(20) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `fax` VARCHAR(60) NULL,
  `created_by` VARCHAR(60) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_by` VARCHAR(60) NULL,
  `updated_date` DATETIME NULL,
  PRIMARY KEY (`contact_id`),
  INDEX `fk_employee_contact_employees1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_contact_employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mymanager`.`employees` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`employee_contact_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`employee_contact_history` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`employee_contact_history` (
  `contact_id` INT(200) NOT NULL,
  `employee_id` VARCHAR(60) NOT NULL,
  `telephone` INT(20) NULL,
  `celular` INT(20) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `fax` VARCHAR(60) NULL,
  `created_by` VARCHAR(60) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_by` VARCHAR(60) NULL,
  `updated_date` DATETIME NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`employee_documents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`employee_documents` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`employee_documents` (
  `document_name` TEXT(100) NULL,
  `document_type` VARCHAR(45) NOT NULL,
  `document_file` LONGBLOB NULL,
  `file_type` VARCHAR(5) NOT NULL,
  `document_number` INT(200) NOT NULL AUTO_INCREMENT,
  `employee_id` VARCHAR(60) NOT NULL,
  `created_by` VARCHAR(60) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_by` VARCHAR(60) NULL,
  `updated_date` DATETIME NULL,
  INDEX `fk_employee_documents_employees1_idx` (`employee_id` ASC) VISIBLE,
  INDEX `fk_employee_documents_file_types1_idx` (`file_type` ASC) VISIBLE,
  PRIMARY KEY (`document_number`),
  CONSTRAINT `fk_employee_documents_employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mymanager`.`employees` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_documents_file_types1`
    FOREIGN KEY (`file_type`)
    REFERENCES `mymanager`.`file_types` (`file_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`employee_documents_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`employee_documents_history` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`employee_documents_history` (
  `document_name` TEXT(100) NULL,
  `document_type` VARCHAR(45) NOT NULL,
  `document_file` LONGBLOB NULL,
  `file_type` VARCHAR(5) NOT NULL,
  `document_number` INT(200) NOT NULL,
  `employee_id` VARCHAR(60) NOT NULL,
  `created_by` VARCHAR(60) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_by` VARCHAR(60) NULL,
  `updated_date` DATETIME NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`employee_payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`employee_payments` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`employee_payments` (
  `payment_id` INT(100) NOT NULL AUTO_INCREMENT,
  `payment_type` VARCHAR(10) NOT NULL,
  `employee_id` VARCHAR(60) NOT NULL,
  `currency` VARCHAR(10) NOT NULL,
  `payment_amount` FLOAT NOT NULL,
  `payment_desc` TEXT NOT NULL,
  `created_by` VARCHAR(60) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_by` VARCHAR(60) NULL,
  `updated_date` DATETIME NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `fk_emplyee_payments_payment_type1_idx` (`payment_type` ASC) VISIBLE,
  INDEX `fk_emplyee_payments_employees1_idx` (`employee_id` ASC) VISIBLE,
  INDEX `fk_emplyee_payments_currencies1_idx` (`currency` ASC) VISIBLE,
  CONSTRAINT `fk_emplyee_payments_payment_type1`
    FOREIGN KEY (`payment_type`)
    REFERENCES `mymanager`.`payment_type` (`payment_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emplyee_payments_employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mymanager`.`employees` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emplyee_payments_currencies1`
    FOREIGN KEY (`currency`)
    REFERENCES `mymanager`.`currencies` (`currency`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`employee_payments_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`employee_payments_history` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`employee_payments_history` (
  `payment_id` INT(100) NOT NULL,
  `payment_type` VARCHAR(10) NOT NULL,
  `employee_id` VARCHAR(60) NOT NULL,
  `currency` VARCHAR(10) NOT NULL,
  `payment_amount` FLOAT NOT NULL,
  `payment_desc` TEXT NOT NULL,
  `created_by` VARCHAR(60) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_by` VARCHAR(60) NULL,
  `updated_date` DATETIME NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`employees` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`employees` (
  `employee_id` VARCHAR(60) NOT NULL,
  `first_name` VARCHAR(60) NOT NULL,
  `last_name` VARCHAR(60) NOT NULL,
  `middle_name` VARCHAR(60) NULL,
  `birthday` DATETIME NOT NULL,
  `birthplace` VARCHAR(100) NOT NULL,
  `gender` ENUM('M', 'F', 'T', 'O') NOT NULL,
  `job_id` INT NULL,
  `department_id` INT NULL,
  `project_name` VARCHAR(60) NULL,
  `created_by` VARCHAR(60) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_by` VARCHAR(60) NULL,
  `updated_date` DATETIME NULL,
  PRIMARY KEY (`employee_id`),
  INDEX `fk_employees_jobs1_idx` (`job_id` ASC) VISIBLE,
  INDEX `fk_employees_departments1_idx` (`department_id` ASC) VISIBLE,
  INDEX `fk_employees_projects1_idx` (`project_name` ASC) VISIBLE,
  CONSTRAINT `fk_employees_jobs1`
    FOREIGN KEY (`job_id`)
    REFERENCES `mymanager`.`jobs` (`job_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `mymanager`.`departments` (`department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_projects1`
    FOREIGN KEY (`project_name`)
    REFERENCES `mymanager`.`projects` (`project_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`employees_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`employees_history` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`employees_history` (
  `employee_id` VARCHAR(60) NOT NULL,
  `first_name` VARCHAR(60) NOT NULL,
  `last_name` VARCHAR(60) NOT NULL,
  `middle_name` VARCHAR(60) NULL,
  `birthday` DATETIME NOT NULL,
  `birthplace` VARCHAR(100) NOT NULL,
  `gender` ENUM('M', 'F', 'T', 'O') NOT NULL,
  `job_id` INT NULL,
  `department_id` INT NULL,
  `project_name` VARCHAR(60) NULL,
  `created_by` VARCHAR(60) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_by` VARCHAR(60) NULL,
  `updated_date` DATETIME NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`file_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`file_types` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`file_types` (
  `file_type` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`file_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`job_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`job_history` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`job_history` (
  `employee_id` VARCHAR(60) NOT NULL,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  `job_id` VARCHAR(45) NULL,
  `department_id` VARCHAR(45) NULL,
  `created_by` VARCHAR(60) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_by` VARCHAR(60) NULL,
  `updated_date` DATETIME NULL,
  CONSTRAINT `fk_job_history_employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mymanager`.`employees` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`job_history_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`job_history_history` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`job_history_history` (
  `employee_id` VARCHAR(60) NOT NULL,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  `job_id` VARCHAR(45) NULL,
  `department_id` VARCHAR(45) NULL,
  `created_by` VARCHAR(60) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_by` VARCHAR(60) NULL,
  `updated_date` DATETIME NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`jobs` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`jobs` (
  `job_id` INT NOT NULL AUTO_INCREMENT,
  `job_title` VARCHAR(60) NOT NULL,
  `min_salary` FLOAT NULL,
  `max_salary` FLOAT NULL,
  `created_by` VARCHAR(60) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_by` VARCHAR(60) NULL,
  `updated_date` DATETIME NULL,
  PRIMARY KEY (`job_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`jobs_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`jobs_history` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`jobs_history` (
  `job_id` INT NOT NULL,
  `job_title` VARCHAR(60) NOT NULL,
  `min_salary` FLOAT NULL,
  `max_salary` FLOAT NULL,
  `created_by` VARCHAR(60) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_by` VARCHAR(60) NULL,
  `updated_date` DATETIME NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`payment_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`payment_type` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`payment_type` (
  `payment_type` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`payment_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`projects` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`projects` (
  `project_name` VARCHAR(60) NOT NULL,
  `description` TEXT NULL,
  `customer` VARCHAR(60) NOT NULL,
  `country` VARCHAR(20) NOT NULL,
  `created_by` VARCHAR(60) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_by` VARCHAR(60) NULL,
  `updated_date` DATETIME NULL,
  PRIMARY KEY (`project_name`),
  INDEX `fk_projects_countries1_idx` (`country` ASC) VISIBLE,
  CONSTRAINT `fk_projects_countries1`
    FOREIGN KEY (`country`)
    REFERENCES `mymanager`.`countries` (`country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`user_adress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`user_adress` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`user_adress` (
  `adress_id` INT(200) NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(60) NOT NULL,
  `country` VARCHAR(20) NOT NULL,
  `city` VARCHAR(60) NOT NULL,
  `street_name` VARCHAR(60) NOT NULL,
  `zipcode` INT NULL,
  `building` VARCHAR(60) NULL,
  `created_by` VARCHAR(60) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_by` VARCHAR(60) NULL,
  `updated_date` DATETIME NULL,
  INDEX `fk_user_adress_countries1_idx` (`country` ASC) VISIBLE,
  PRIMARY KEY (`adress_id`),
  INDEX `fk_user_adress_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_adress_countries1`
    FOREIGN KEY (`country`)
    REFERENCES `mymanager`.`countries` (`country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_adress_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mymanager`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`user_adress_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`user_adress_history` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`user_adress_history` (
  `adress_id` INT(200) NOT NULL,
  `user_id` VARCHAR(60) NOT NULL,
  `country` VARCHAR(20) NOT NULL,
  `city` VARCHAR(60) NOT NULL,
  `street_name` VARCHAR(60) NOT NULL,
  `zipcode` INT NULL,
  `building` VARCHAR(60) NULL,
  `created_by` VARCHAR(60) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_by` VARCHAR(60) NULL,
  `updated_date` DATETIME NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`user_contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`user_contact` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`user_contact` (
  `contact_id` INT(200) NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(60) NOT NULL,
  `telephone` INT NULL,
  `celular` INT NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `fax` VARCHAR(60) NULL,
  `created_by` VARCHAR(60) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_by` VARCHAR(60) NULL,
  `updated_date` DATETIME NULL,
  PRIMARY KEY (`contact_id`),
  INDEX `fk_user_contact_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_contact_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mymanager`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`user_contact_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`user_contact_history` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`user_contact_history` (
  `contact_id` INT(200) NOT NULL,
  `user_id` VARCHAR(60) NOT NULL,
  `telephone` INT NULL,
  `celular` INT NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `fax` VARCHAR(60) NULL,
  `created_by` VARCHAR(60) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_by` VARCHAR(60) NULL,
  `updated_date` DATETIME NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`users` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`users` (
  `user_id` VARCHAR(60) NOT NULL,
  `user_type` VARCHAR(60) NOT NULL,
  `first_name` VARCHAR(60) NOT NULL,
  `last_name` VARCHAR(60) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `birthday` DATE NOT NULL,
  `birthplace` VARCHAR(100) NOT NULL,
  `gender` ENUM('M', 'F', 'T', 'O') NOT NULL,
  `rights` VARCHAR(60) NOT NULL,
  `created_by` VARCHAR(60) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_by` VARCHAR(60) NULL,
  `updated_date` DATETIME NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`users_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`users_history` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`users_history` (
  `user_id` VARCHAR(60) NOT NULL,
  `user_type` VARCHAR(60) NOT NULL,
  `first_name` VARCHAR(60) NOT NULL,
  `last_name` VARCHAR(60) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `birthday` DATETIME NULL,
  `birthplace` VARCHAR(100) NULL,
  `gender` ENUM('M', 'F', 'T', 'O') NOT NULL,
  `rights` VARCHAR(60) NOT NULL,
  `created_by` VARCHAR(60) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_by` VARCHAR(60) NULL,
  `updated_date` DATETIME NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`user_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`user_type` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`user_type` (
  `user_type` ENUM('HR', 'ASSISTANT', 'MANAGER', 'ADMIN', 'FINANCE') NOT NULL,
  PRIMARY KEY (`user_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`working_hours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`working_hours` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`working_hours` (
  `index` INT(100) NOT NULL AUTO_INCREMENT,
  `employee_id` VARCHAR(60) NOT NULL,
  `date` DATE NOT NULL,
  `amount` FLOAT NOT NULL,
  `created_by` VARCHAR(60) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_by` VARCHAR(60) NULL,
  `updated_date` DATETIME NULL,
  PRIMARY KEY (`index`),
  INDEX `fk_working_hours_employees1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_working_hours_employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mymanager`.`employees` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymanager`.`working_hours_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymanager`.`working_hours_history` ;

CREATE TABLE IF NOT EXISTS `mymanager`.`working_hours_history` (
  `index` INT(100) NOT NULL,
  `employee_id` VARCHAR(60) NOT NULL,
  `date` DATE NOT NULL,
  `amount` FLOAT NOT NULL,
  `created_by` VARCHAR(60) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_by` VARCHAR(60) NULL,
  `updated_date` DATETIME NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;