applicationName: MyManager

database:
  name: mymanager-db
  type: mysql
  driverClassName: com.mysql.cj.jdbc.Driver
  jdbcUrl: jdbc:mysql://localhost:3306/mymanager
  username: root
  password: P4ssw0rd
  ssl: false
  datasourceProperties:
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048


    
